# Simple ingress without ingress class - should work with any ingress controller
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-simple-ingress
  namespace: microservices-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: microservices.192.168.101.191.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
    - host: sock-shop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80