apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices-demo  # <--- Add this line!
resources:
  - ../../base
  - front-end-hpa.yaml
  - simple-nodeport.yaml
  - working-ingress.yaml
