apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metrics-server-pdb
  namespace: metrics-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
