apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - production-policies.yaml

commonLabels:
  app.kubernetes.io/name: microservices-demo
  app.kubernetes.io/component: network-security
  app.kubernetes.io/managed-by: kustomize