piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:4gd-Lakeshirts/cluster-infra.git
    targetRevision: main
    path: infrastructure/kasten-io/overlays/prod
    kustomize:
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

