apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kasten.io/
    chart: k10
    targetRevision: 8.0.5
    helm:
      values: |
        global:
          persistence:
            storageClass: standard
          clusterName: onprem-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

