apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4gd-Lakeshirts/cluster-infra
    targetRevision: HEAD
    path: infrastructure/kasten-io/overlays/prod
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true

