apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4gd-Lakeshirts/cluster-infra
    targetRevision: HEAD
    path: infrastructure/metrics-server/overlays/prod
    directory:
      recurse: true  # ✅ Keep this if you're including subfolders or patch files
    kustomize:
      enableHelm: true  # ✅ Required for using HelmChartInflationGenerator
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
